### PR TITLE
Include dependencies in the package

### LINKED ISSUE #401: Publish WinGet as an MSIX with dependencies included
# Description of the new feature/enhancement

Publish the WinGet installer as an MSIX with the dependencies included, just like Windows Terminal.

# Motivation

Currently, the WinGet `.appxbundle` has two required dependencies from `VCLibs`. This prevents people to install in environments where there is no Microsoft Store available, such as the Windows Sandbox. This would help https://github.com/microsoft/winget-pkgs/pull/827.

# Proposed technical implementation details

Follow the same approach of Windows Terminal, tracked on https://github.com/microsoft/terminal/issues/3097 and https://github.com/microsoft/terminal/pull/5661.

This can also help -> https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net

### PR DESCRIPTION
**Pull request by felipecrs**
Closes #401.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-cli/pull/456)

### CODE REVIEW

**Comment by felipecassiors** [comment]
Well, I spent a big amount of hours trying to generate an Appx from the project. I was able to, but the resultant Appx doesn't seem to make `winget` available at the system after installing.

However, studying https://github.com/microsoft/terminal/pull/5661 I noticed that the goal is to include some `.dll`s into the compilation. I struggled with that, and I'm don't even know how can I evaluate if it works or not, since I could not build a working `Appx`.

Other changes are related to unset the dependencies of the Appx manifest, and they worked as expected.

**Comment by felipecassiors** [comment]
I would **really** appreciate any help on this.

**Comment by yao-msft** [comment]
> Well, I spent a big amount of hours trying to generate an Appx from the project. I was able to, but the resultant Appx doesn't seem to make winget available at the system after installing.

The AppInstallerCliPackage project is for dev testing only. The generated appx uses wingetdev as execution alias.
By the way, there have been internal discussions on ways of distributing dependency dlls. We'll get back when a decision is made.
Thanks.

**Comment by felipecassiors** [comment]
> The AppInstallerCliPackage project is for dev testing only. The generated appx uses wingetdev as execution alias.

Awesome! The `wingetdev` was all I need! I suggest to include it in the documentation if it's not already.

**Comment by felipecassiors** [comment]
Believe you or not, I was able to use `wingetdev` without the VCLibs dependencies with the package created by this PR. 

Take a look (click on the GIF to see it in full quality):
u8Z39jxm0o

**Comment by JohnMcPMS** [comment]
Closing as this as it has been in draft the entire time (almost its 🍰 ) and we now have VS publishing the framework packages for easier consumption.

**Pull request closed without merging**
