### PR TITLE
Add User Setting controlling Path Tokenization

### PR DESCRIPTION
**Pull request by Trenly**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [x] This pull request is related to an issue. #1977

Some users may not want their paths to be replaced with environment variables when displayed. This PR adds a setting to control whether the paths are tokenized or not. 

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/3209)

### CODE REVIEW

**Comment by Trenly** [comment]
@yao-msft - When re-running the tests locally I get similar messages for several tests. Is this the same error the pipeline is showing?
```
D:\Git\winget-cli\src\AppInstallerCLITests\AdminSettings.cpp(19): FAILED:
  REQUIRE( EnableAdminSetting(AdminSetting::LocalManifestFiles) )
due to unexpected exception with message:
  D:\Git\winget-cli\src\AppInstallerCommonCore\Settings.cpp(309)\
  AppInstallerCLITests.exe!00007FF708BC02DE: (caller: 00007FF708E303CB)
  Exception(1) tid(5f04) 800F024B The hash for the file is not present in the
  specified catalog file. The file is likely corrupt or the victim of
  tampering.
      [AppInstaller::Settings::`anonymous-namespace'::SecureSettingsContainer::
  Get(!verData.Found)]
```

**Comment by yao-msft** [comment]
The failure test case is:

SettingsAnonymizePathForDisplay/Invalid Value

with:

FAILED:
  REQUIRE( userSettingTest.GetWarnings().size() == 1 )
with expansion:
  2 == 1
at D:\a\1\s\src\AppInstallerCLITests\UserSettings.cpp(243)

Maybe set a breakpoint to see why 2 warnings instead of 1 warnings?

**Comment by Trenly** [comment]
> The failure test case is:
> 
> SettingsAnonymizePathForDisplay/Invalid Value
> 
> with:
> 
> FAILED: REQUIRE( userSettingTest.GetWarnings().size() == 1 ) with expansion: 2 == 1 at D:\a\1\s\src\AppInstallerCLITests\UserSettings.cpp(243)
> 
> Maybe set a breakpoint to see why 2 warnings instead of 1 warnings?

It seems to be complaining about data type when I try to load the settings file. I'm taking a guess that its because the string value isn't quoted and is malformed JSON. If the latest commit doesn't fix the test, I'm not sure what the second error would be

**Review by yao-msft — APPROVED** [review]

**Pull request merged**
