### PR TITLE
Adding troubleshooting

### PR DESCRIPTION
**Pull request by denelon**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Are you working against an Issue?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1134)

### CODE REVIEW

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/251

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/612

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/663

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/671

**Review by JohnMcPMS — APPROVED** [review]

**Pull request merged**
