### PR TITLE
Fix bugs with display paths

### PR DESCRIPTION
**Pull request by JohnMcPMS**
## Change
This change fixes two bugs with display paths:
1. The recent change to use case insensitive ICU for directory name equality inverted the comparison, making the replacement not happen correctly.
2. The recent change to enable display paths generically left them marked for creation, resulting in errors if directories that required administrator privileges to create did not exist and were requested from an unelevated context (ex. run `winget --info` from medium IL process when the portable machine links location(s) did not exist).

In addition, I tried to generally make `forDisplay` apply broadly since it is now allowed to be requested on any path.

## Validation
`winget --info` now contains the expected output instead of an error (2) or the full paths containing the user's account name (1).
A few unit tests that were being hit by the error are also working now.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/3157)

### CODE REVIEW

**Comment by Trenly** [comment]
Thank you for fixing everything I broke

**Review by yao-msft — APPROVED** [review]

**Comment by msftrubengu** [comment]
Blaming cosmic rays 👾

**Pull request merged**
