### PR TITLE
Add argument for ignoring warnings

### LINKED ISSUE #3405: `winget validate` returns a non-zero exit code if `Agreements` are present
### Brief description of your issue

I forsee this being a problem for when our organization gets verified as the developer of package we submit.

We create our winget PRs via automated GitHub actions upon releasing. As part of this process, we run `winget validate` on the manifest to be uploaded. If we want to add an `Agreements` section in the future, we have no way to suppress the warning that having that section creates.

Can we have a flag to disable this warning or some other way to get a zero exit code with `Agreements` present?

### Steps to reproduce

1. Add an `Agreements` section to a manifest with at least one entry.
2. Run `winget validate` on the manifest.
3. Check the exit code.

### Expected behavior

A zero exit code or a way to suppress the error

### Actual behavior

```ps
PS S:\workspace\tgstation-server\build\package\winget\manifest> winget validate --manifest .
Manifest validation succeeded with warnings.
Manifest Warning: Field usage requires verified publishers. [Agreements]

PS S:\workspace\tgstation-server\build\package\winget\manifest> echo $LastExitCode
-1978335192
```

### Environment

```shell
PS S:\workspace\tgstation-server\build\package\winget\manifest> winget --info
Windows Package Manager (Preview) v1.6.1573-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.3086
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```
```

### PR DESCRIPTION
**Pull request by Trenly**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [x] This pull request is related to an issue.
  - Resolves #3405

I wasn't sure whether or not to go with a new exit code, or keep it as a 0 exit code as mentioned in the linked issue. I ended up deciding to go with what was written in the issue as it seemed like a very specific use case. If a non-zero exit code would be a better option, I was thinking that `--suppress-warnings` could be separated from `--ignore-warnings` where ignoring completely ignores them and suppressing will hide the output but return a new exit code if there were warnings that were suppressed.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/3572)

### CODE REVIEW

**Review by Cyberboss — APPROVED** [review]

**Comment by Trenly** [comment]
> /azp run

Thanks for putting up with me 😄

**Review by yao-msft — APPROVED** [review]

**Pull request merged**
