### PR TITLE
Rc v1.2.10271 fixes

### PR DESCRIPTION
**Pull request by Alfredo229**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Are you working against an Issue?

-----

I would like to install the 'winget' powershell command to uninstall Windows 11 Widgets.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2317)

### CODE REVIEW

**Comment by Alfredo229** [comment]
I've signed up for a 'Windows Insider' client.
I've been regularly attacked.
I hope my "baitness" can help improve security.

I'd like to point out 2 issues i've noticed.
-There is regularly an extra 'windows explorer' process running with 5mb memory.
-There is a rare (null) process, linked with a widget activity.

If i am to recreate those issues i no longer need the command.

**Comment by Alfredo229** [comment]
I want to drop this pull.

**Comment by Alfredo229** [comment]
Nevermind. Big shiny button.

**Review by Alfredo229 — COMMENTED** [review]
Trying to rollback this thing. I should NOT have erite priviledges.

**Comment by Masamune3210** [comment]
You have write permissions to your own branch, that's how pull requests work. You clone, do your work, and then request that any work you did be reviewed for pull back into the main repo. You can do whatever in your own copy, it doesn't affect anything here unless the request is approved

**Pull request closed without merging**
