### PR TITLE
Remove phrase

### PR DESCRIPTION
**Pull request by phrocker**
Just a little cleanup!

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-cli/pull/295)

### CODE REVIEW

**Comment by JohnMcPMS** [comment]
While I agree with the sentiment, this is a subtree of the [yaml-cpp](https://github.com/jbeder/yaml-cpp) project.  I would rather not update the file directly so as to not have the management overhead of potential merge conflicts.

**Comment by phrocker** [comment]
I see that now. I'll change the source of the pr and send it there. Thanks!

**Comment by JohnMcPMS** [comment]
Policheck is mad at us for this now, and I see that your PR to yaml-cpp didn't result in success.  So I guess we have to take the overhead and make the change.  Let's see how well this PR works when necro'd.

**Pull request merged**
