### PR TITLE
Setting DefaultLocale's default value to "en-US"

### PR DESCRIPTION
**Pull request by palenshus**
Nice to have a default value, and enables our codegen'd object model to have a default value set for this property

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1170)

### CODE REVIEW

**Comment by palenshus** [comment]
@denelon, thoughts?

**Comment by denelon** [comment]
I've seen one or two packages submitted with other defaultLocale values. I don't mind having a default as long as the user can change it if they wish.

**Comment by JohnMcPMS** [comment]
> Nice to have a default value, and enables our codegen'd object model to have a default value set for this property

I don't think we actually do want a default here; I would rather it be required to be provided rather than accidentally forgotten (and then potentially wrong).

**Comment by palenshus** [comment]
> I don't think we actually do want a default here; I would rather it be required to be provided rather than accidentally forgotten (and then potentially wrong).

Setting a default [doesn't mean it's not required](https://json-schema.org/understanding-json-schema/reference/generic.html#:~:text=The%20default%20keyword%20specifies%20a%20default%20value%20for,in%20which%20it%20resides%2C%20but%20that%20isn%E2%80%99t%20required.), validation will still fail if the property is missing altogether. This just gives a nice default value to codegen tools like ours

**Review by jjvrmorales367 — APPROVED** [review]
I'm gonna ive it a trial

**Comment by JohnMcPMS** [comment]
> > I don't think we actually do want a default here; I would rather it be required to be provided rather than accidentally forgotten (and then potentially wrong).
> 
> Setting a default [doesn't mean it's not required](https://json-schema.org/understanding-json-schema/reference/generic.html#:~:text=The%20default%20keyword%20specifies%20a%20default%20value%20for,in%20which%20it%20resides%2C%20but%20that%20isn%E2%80%99t%20required.), validation will still fail if the property is missing altogether. This just gives a nice default value to codegen tools like ours

Did you verify that `validate` still properly fails when a file is missing this value?

**Comment by yao-msft** [comment]
> > > I don't think we actually do want a default here; I would rather it be required to be provided rather than accidentally forgotten (and then potentially wrong).
> > 
> > 
> > Setting a default [doesn't mean it's not required](https://json-schema.org/understanding-json-schema/reference/generic.html#:~:text=The%20default%20keyword%20specifies%20a%20default%20value%20for,in%20which%20it%20resides%2C%20but%20that%20isn%E2%80%99t%20required.), validation will still fail if the property is missing altogether. This just gives a nice default value to codegen tools like ours
> 
> Did you verify that `validate` still properly fails when a file is missing this value?

IIRC, the default field is not used during schema validation. So it won't break the "validate". We have semantic validation that the DefaultLocale field in version manifest must match PackageLocale field in defaultLocale manifest. Shall we update the defaultLocale schema to default to en-US to be consistent too?

**Comment by palenshus** [comment]
@yao-msft is correct, we have many other default values already, which winget validate complains if they aren't set (for example, ManifestType, ManifestVersion, etc). And Yao yes I think it would make sense to default the PackageLocale to that as well

**Comment by palenshus** [comment]
@yao-msft, @JohnMcPMS, @denelon, ping

**Comment by denelon** [comment]
@palenshus I don't see this as a problem, we just need to be very careful about schema changes, and we're currently working on the v1.1 schema so we should make sure to be consistent across all of the product area.

**Comment by yao-msft** [comment]
> @yao-msft, @JohnMcPMS, @denelon, ping

@palenshus, can you send a new commit changing the defaultLocale schema to default to en-US as well, so I can just approve and merge?

**Review by yao-msft — APPROVED** [review]

**Pull request merged**
