### PR TITLE
Portable Support as Stable Feature

### PR DESCRIPTION
**Pull request by ryfu-msft**
Changes:
- Makes support for portable apps stable and removes all code related to portable as an experimental feature.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2233)

### CODE REVIEW

**Review by JohnMcPMS — APPROVED** [review]

**Comment by Trenly** [comment]
What are the MSFT devs doing online at this hour? 🤔

**Comment by denelon** [comment]
> What are the MSFT devs doing online at this hour? 🤔

I'm guessing they are trying to button up 1.3 to get it ready for a release candidate build 😁

They can flex their hours as they see fit now. Sometimes they like the features they are working on too 🤪

**Comment by hickford** [comment]
Please document this feature at https://learn.microsoft.com/en-us/windows/package-manager/package/manifest

**Comment by denelon** [comment]
@hickford are you referring to the [schema for the manifests](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.5.0/installer.md) or something else?

**Pull request merged**
