### PR TITLE
Add Arm64 to list of architectures in Module Initialization.

### PR DESCRIPTION
**Pull request by snickler**
- [X] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [X] This pull request is related to an issue.
  - Resolves: #4169
-----

This PR addresses an issue that prevents the WinGet Cmdlets from loading in an Arm64 PowerShell 7.x environment.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4251)

### CODE REVIEW

**Comment by yao-msft** [comment]
Currently the arm64 modules are not published. We'll need to validate the arm64 modules and make an internal pipeline changes to publish them. Then we can take in this change. Thanks.

**Comment by snickler** [comment]
> Currently the arm64 modules are not published. We'll need to validate the arm64 modules and make an internal pipeline change to publish them. Then we can take in this change. Thanks.

That answered the question I meant to ask earlier because I noticed it's only building `x64` and `x86` in the `azure-pipelines` and I figured that would be one of those changes that could potentially be a breaking one. 

Thanks for the clarification!

**Comment by denelon** [comment]
@snickler thanks for the PR! We've been going through a lot of churn with our build pipelines and new internal requirements. Thanks so much for calling this out and doing something about it.

**Comment by msftrubengu** [comment]
@snickler where you able to run the module locally?

**Comment by snickler** [comment]
> @snickler where you able to run the module locally?

I'm able to run the module locally to some extent. I'm trying to figure out what it's complaining about, but I believe it MAY have to do with the Any CPU projects. I'm now getting a ` Exception has been thrown by the target of an invocation` error when running the commands specific to retrieving WinGet Source details and packages. Once I figure out what's happening here, I *MAY* have something usable. I think I'll make a separate PR for that effort.

**Comment by msftrubengu** [comment]
@snickler I was able to repro that AV using the non packaged version of PowerShell 7 for arm64. Yes, the package got installed and PowerShell crashed. Regardless, there's a known issue with running the module in the packaged version of PowerShell for all architectures that we want to address before calling it good for ARM64. Specially because winget's default installation of PowerShell in arm64 is the msix.

**Comment by msftrubengu** [comment]
@snickler I created #4392 to enable arm64 for this module. Once that is merged, I'll merge this for the `Initialize-LocalWinGetModules.ps1`. Sorry it took this long.

**Comment by snickler** [comment]
> @snickler I created #4392 to enable arm64 for this module. Once that is merged, I'll merge this for the `Initialize-LocalWinGetModules.ps1`. Sorry it took this long.

It's no problem. Happy to see it!

**Review by msftrubengu — APPROVED** [review]

**Pull request merged**
