### PR TITLE
Fix German localization resource file, especially many odd translations regarding packages and pinning

### PR DESCRIPTION
**Pull request by igorakkerman**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [x] This pull request is related to an issue.

-----

Fixes https://github.com/microsoft/winget-cli/issues/3966

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4133)

### CODE REVIEW

**Comment by igorakkerman** [comment]
@microsoft-github-policy-service agree

**Comment by Trenly** [comment]
> Files under Localization folder will be overwritten when we do a localization update, so no changes under Localization folder will take effect.
_Originally posted by @yao-msft in https://github.com/microsoft/winget-cli/issues/3250#issuecomment-1551990405_

Someone at MSFT will need to submit these to the internal localization team

**Comment by igorakkerman** [comment]
Fixes #3966

**Comment by yao-msft** [comment]
Thanks for your suggestion, @igorakkerman 

For winget team: I have created bug [BUG 48808197](https://microsoft.visualstudio.com/OS/_workitems/edit/48808197) for localization team consideration.

We'll close the bug after localization team takes in the suggestions, and after winget's next localization refresh.

**Comment by denelon** [comment]
The latest localization patches were included in WinGet 1.8. I'm going to go ahead and close this PR.

**Comment by igorakkerman** [comment]
I don't see any of the changes from this PR in the latest resource file. Is it safe to assume that they were rejected by your localization team in your internal review process?

**Comment by ItzLevvie** [comment]
It is also important to note Microsoft's German style guide from https://aka.ms/german-styleguide which states "However, in order to offset the actual product name from the word that follows in a compound, the hyphen is placed right between the product name and the following term."

I am not German but based on that "Windows-Paket-Manager" could be correct here.

**Comment by igorakkerman** [comment]
Thanks a lot, @JohnMcPMS . I agree that using the German term "Paket" for the English term "package" in German strings is preferable to what I suggested originally.

**Pull request closed without merging**
