### PR TITLE
Add additional switches for Inno Setup based installers

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [ ] This pull request is related to an issue.

-----

This PR will add two additional switches for Inno Setup based installers. According to [Inno Setup Help](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline):

- > `/SP-`  disables the This will install... Do you wish to continue? prompt at the beginning of Setup.

  There are some cases for this switch such as `JLC.EasyEDA.Pro` and `JLC.LCEDA.Pro`, where simply using `/VERYSILENT` can not suppress this dialog box:
  image

- > `/SUPPRESSMSGBOXES` instructs Setup to suppress message boxes. Only has an effect when combined with `/SILENT` or `/VERYSILENT`.
  > The default response in situations where there's a choice is:
  > 
  > Yes in a 'Keep newer file?' situation.
  > No in a 'File exists, confirm overwrite.' situation.
  > Abort in Abort/Retry situations.
  > Cancel in Retry/Cancel situations.
  > Yes (=continue) in a DiskSpaceWarning/DirExists/DirDoesntExist/NoUninstallWarning/ExitSetupMessage/ConfirmUninstall situation.
  > Yes (=restart) in a FinishedRestartMessage/UninstalledAndNeedsRestart situation.
The recommended choice in a PrivilegesRequiredOverridesAllowed=dialog situation.

  This switch is useful when errors occurred during silent installation, so the installation will be aborted immediately instead of getting stuck.

  image
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/3562)

### CODE REVIEW

**Comment by Trenly** [comment]
Sometimes the message boxes are important though. I recall some dicussion about it previously -
 https://github.com/microsoft/winget-cli/issues/2093#issuecomment-1099306185

**Comment by SpecterShell** [comment]
> Sometimes the message boxes are important though. I recall some dicussion about it previously - [#2093 (comment)](https://github.com/microsoft/winget-cli/issues/2093#issuecomment-1099306185)

Users can also refer to the logs for information about errors:
```
2023-08-28 00:44:32.525   -- File entry --
2023-08-28 00:44:32.525   Dest filename: C:\Users\SpecterShell\AppData\Local\Programs\WinSCP\PuTTY\pageant.exe
2023-08-28 00:44:32.525   Time stamp of our file: 2023-06-21 11:00:48.000
2023-08-28 00:44:32.525   Dest file exists.
2023-08-28 00:44:32.525   Time stamp of existing file: 2023-06-21 11:00:48.000
2023-08-28 00:44:32.525   Installing the file.
2023-08-28 00:44:32.539   DeleteFile: The existing file appears to be in use (5). Retrying.
2023-08-28 00:44:33.549   DeleteFile: The existing file appears to be in use (5). Retrying.
2023-08-28 00:44:34.563   DeleteFile: The existing file appears to be in use (5). Retrying.
2023-08-28 00:44:35.576   DeleteFile: The existing file appears to be in use (5). Retrying.
2023-08-28 00:44:36.586   Defaulting to Abort for suppressed message box (Abort/Retry/Ignore):
                          C:\Users\SpecterShell\AppData\Local\Programs\WinSCP\PuTTY\pageant.exe
                          
                          An error occurred while trying to replace the existing file:
                          DeleteFile failed; code 5.
                          Access is denied.
2023-08-28 00:44:36.586   User canceled the installation process.
2023-08-28 00:44:36.586   Rolling back changes.
2023-08-28 00:44:36.587   Starting the uninstallation process.
2023-08-28 00:44:36.587   Uninstallation process succeeded.
2023-08-28 00:44:36.587   Deinitializing Setup.
2023-08-28 00:44:36.587   Preparing installation report
2023-08-28 00:44:36.587   Sending installation report: https://winscp.net/install.php?mode=report&installed=0&silent=1&ver=6.1.1&lang=en&prevver=6.1.1&sponsorstatus=N&sponsor=&sponsoringclicked=0&
2023-08-28 00:44:37.440   Installation report send result: 200 OK
2023-08-28 00:44:37.448   Log closed.
```

**Comment by yao-msft** [comment]
Hi @denelon, what will be your thought on this?

Mainly for Inno installers, in some cases, /SILENT and /VERYSILENT may still have message box pops up unless /SUPPRESSMSGBOXES is also provided.

There are discussions around this, sometimes the message box are important as Trenly linked above https://github.com/microsoft/winget-cli/issues/2093#issuecomment-1099306185

Do we prefer suppressing the msg boxes and let install fail for silent and silentWithProgress flows? Or keep the existing behavior and let individual installer decide whether to pop up msg box when they need the user input in silent and silentWithprogress flows?

**Comment by denelon** [comment]
For WinGet, silent should be a zero UI experience.
The default "Silent with Progress" can show UI but cannot prompt.

@Trenly do you care to weigh in here?

**Comment by JohnMcPMS** [comment]
> For WinGet, silent should be a zero UI experience. The default "Silent with Progress" can show UI but cannot prompt.

Agree, neither should allow for any blocking.  They either succeed or fail, they do not wait indefinitely for a user interaction.

**Comment by Trenly** [comment]
This can already be set at the manifest level using the Silent and SilentWithProgress parameters.

While the examples given do return error codes in the logs and exit with a non-zero exit code, I could very easily see other applications that simply continue and result in a broken install - either due to missing dependencies, system incompatibility, etc.

On the other hand, I believe there are also applications in the repo today that have an auto-update check, which the /suppressmsgboxes will avoid, but that currently don’t specify the switch. However - all latest versions should still install silently in these cases. But then to @OfficialEsco's point in the original linked issue - some users may want to be notified that they are installing an outdated version.

According to the [documentation](https://jrsoftware.org/ishelp/index.php?topic=setupcmdline), suppressing message boxes defaults to selecting "yes" for certain prompts
> Yes (=continue) in a DiskSpaceWarning/DirExists/DirDoesntExist/NoUninstallWarning/ExitSetupMessage/ConfirmUninstall situation.

If winget automatically continues in a DirExists situation, it could lead to user settings being blown away or user files being destroyed unintentionally. I know that we specify the norestart option, so automatically selecting yes on a restart probably won’t do anything, but its possible that not all installers respect norestart.

-----

I'm not sure what is best, but leaving these options to be specified per-manifest seems to be the safest option considering that it will also help identify dependencies, non-standard behavior, and elevation requirements by looking at the prompt on screen during tesing rather than having to dig into logs

**Comment by SpecterShell** [comment]
I tried to specify the target location to a non-empty folder on a small-size partition so I can get the first two types of message boxes in interactive installation. The installer comes from the package `JLC.EasyEDA.Pro` and is based on Inno Setup 6.2.0.
image
image

These message boxes, however, can be skipped by just using the `/SILENT` switch. The installation will still get stuck for not having enough disk space though.
image

**Comment by yao-msft** [comment]
I had several internal discussions with the team in the past. We think "making sure the operation is silent" is still preferred for unattended scenarios. Also user still gets to find the reason for install failure from the logs. So we decided to go with this change.

**Review by yao-msft — APPROVED** [review]

**Pull request merged**
