### PR TITLE
Create #163 - Dependencies.md

### PR DESCRIPTION
**Pull request by denelon**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/954)

### CODE REVIEW

**Comment by jsoref** [comment]
Fwiw, the latest version will do a better job of annotating misspellings (you'll get 10 instead of duplicates).

**Review by JohnMcPMS — APPROVED** [review]
I think this is a fine starting point, but probably needs more details added.  One thing that would be good to add now though would be what we are not planning to do.  For instance, there has been discussion around a produces/consumes model as well, where a package could state that it produces "JRE" and another that it consumes "JRE", but I don't think that we are planning on doing that here.

**Comment by denelon** [comment]
@jsoref some of the misspellings appear to be part of URLs. Is that expected?

**Comment by jsoref** [comment]
@denelon: people make typos in urls, yes :-).

Also, a word that appears in a url if it's real is likely to appear elsewhere.

**Pull request merged**
