### PR TITLE
Add basic proxy support

### LINKED ISSUE #190: Proxy options support
# Description of the new feature/enhancement

Something like:

```powershell
winget install git.git --proxy="http://127.0.0.1:2345"
```

This will make `winget` download `git` through the *proxy server*.

### PR DESCRIPTION
**Pull request by eternalphane**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?

-----

Partially resolves #190.

- [x] `--proxy` option
- [x] `--no-proxy` option (may need a better name, e.g. `proxy-bypass-list`?)
- [x] `network.proxy` settings
- [x] `network.proxyOverride` settings (or `proxyBypass`?)
- [x] `HTTP_PROXY`, `HTTPS_PROXY`, `FTP_PROXY`, `ALL_PROXY`, `NO_PROXY` environment variables

TODOs (not in this pr):

- [ ] authentication
- [ ] PAC
- [ ] protocol-specific proxy settings just like `aria2` (not sure there's much use case)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1776)

### CODE REVIEW

**Comment by denelon** [comment]
@eternalphane to resolve the spelling issue, you may add "stl" in alphabetical order to expect.txt.

We will look at this when we have a few more of the engineering team members back from holidays.

**Comment by denelon** [comment]
Thanks @eternalphane.

Just to let you know, this should be converted to a draft PR. We're going to need to have a security review on this feature. Anything to do with networking requires some internal reviews which will take some calendar time to coordinate with the other required teams.

Thanks so much for the contribution here! I'm sure plenty of users will be thrilled.

**Comment by neoribs** [comment]
Is it already work?

**Comment by lemchen** [comment]
> Is it already working?

Not yet.

**Comment by char-46** [comment]
Is there any newer plan to make it come true?

**Pull request closed without merging**
