### PR TITLE
Update versions and more

### PR DESCRIPTION
**Pull request by skanda890**
- [X] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [X] This pull request is related to #4659.

-----
Commits: 539fa8e8a098cfd04f1bad8e0d2932341cdd6479, 8dde99c24d3d5fd68dfffae598335145eccfd585, 816babc7fb0c05a14948556743f244b1dee684d5, 5ea38cd5ee13139459bf1ecaaeb013b364f4f108, e04fd0cec6f58689ac31cbff3b86e54ca532a01f.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4658)

### CODE REVIEW

**Comment by Trenly** [comment]
@skanda890 - This is pulling in over 1700 commits, some of which have already been made in master. 

You need to reset your master branch and  start a new branch for proposing any changes, otherwise all your PRs will have this same issue. You can use the instructions I sent in Gitter/Element to get your branches into a clean state

**Comment by skanda890** [comment]
Can you add me again?

**Comment by skanda890** [comment]
Changes not done yet.

**Comment by skanda890** [comment]
PR moved to #4663.

**Pull request closed without merging**
