### PR TITLE
Add experimental argument to open logs folder

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?
  - https://github.com/microsoft/winget-cli/issues/2355#issuecomment-1191937273
-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2510)

### CODE REVIEW

**Comment by denelon** [comment]
Does this argument work with any command? Does it display the help across all commands? Maybe a quick spec would make sense for this one. I'm expecting we need to think about how it would interact with the PowerShell cmdlets as well.

**Comment by Trenly** [comment]
> Does this argument work with any command? 

Yes

> Does it display the help across all commands? 

Yes

> Maybe a quick spec would make sense for this one. I'm expecting we need to think about how it would interact with the PowerShell cmdlets as well.

I think it would be a good consideration, but I would suggest instead speccing out all common arguments; How does verbose logs interact with the cmdlets? How does wait interact? 

I also think this could be refined more in the future (hence only mentioning the linked issue, not marking it for closure) as how users interact with logs is a complex subject. I was thinking build in some minimal functionality first, then spec out a larger feature around it?

**Comment by denelon** [comment]
Maybe it should be an experimental argument initially then. It allows us to get feedback before releasing it with the GA client if we need to iterate.

**Comment by denelon** [comment]
Yes, I agree we should cover the other types of arguments as well as they relate to PowerShell.

**Comment by Trenly** [comment]
> Maybe it should be an experimental argument initially then. It allows us to get feedback before releasing it with the GA client if we need to iterate.

Made it experimental

**Review by yao-msft — APPROVED** [review]

**Pull request merged**
