### PR TITLE
Enable MSI testing in CI/CD pipeline

### PR DESCRIPTION
**Pull request by JohnMcPMS**
## Change
Build the test MSI locally and include the binary to enable the CI/CD pipeline to test installing it.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2386)

### CODE REVIEW

**Comment by JohnMcPMS** [comment]
> * emplates

Not every string is a literal, so seeing `\t` does not always mean a tab...

**Review by lechacon — APPROVED** [review]
Would it be possible to add instructions or a script to update the .msi when needed?

**Comment by JohnMcPMS** [comment]
> Would it be possible to add instructions or a script to update the .msi when needed?

It turned out to be "Build for Release/x86".  The cryptic error message you get when you don't choose that is the only thing making it non-obvious.  Where would you suggest putting such instructions?

**Comment by lechacon** [comment]
>  Where would you suggest putting such instructions?

Maybe near to where it is used in the e2etest template, or in a `TestData\README`?

**Pull request merged**
