### PR TITLE
Made all installer types lowercase during `show`.

### LINKED ISSUE #1685: Installer type should be displayed as submitted
### Brief description of your issue

The `winget show` output displays the installer type in Pascal Case. It should be displayed in lower case as submitted in the manifest.

### Steps to reproduce

`winget show <package>`

### Expected behavior

```
Installer:
  Type: msix
```
```
Installer:
  Type: inno
```

etc...

### Actual behavior
```
Installer:
  Type: Msix
```
```
Installer:
  Type: Inno
```

### Environment

```shell
Windows Package Manager v1.1.12702
```

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue?

-----

Resolves #1685.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/1689)

### CODE REVIEW

**Comment by yao-msft** [comment]
This will change the value returned in com api, but maybe it's ok.

**Comment by jedieaston** [comment]
I didn't think about that, although wouldn't the consumers of the COM API probably have the expectation that this value wasn't capitalized oddly?

**Comment by JohnMcPMS** [comment]
The problem is just that if things change, then existing code can break.  The good thing is that this change isn't likely to impact anyone.  It would only affect getting the installer type of installed packages as far as I saw, and I don't know if anyone is even doing that right now.

**Review by JohnMcPMS — APPROVED** [review]

**Pull request merged**
