### PR TITLE
Give System and Admins full access to state folders

### PR DESCRIPTION
**Pull request by yao-msft**
Manually validated the folders have System and Admin access after the change.
This pr could be merged after approval from Intune security team.
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-cli/pull/3471&drop=dogfoodAlpha

### CODE REVIEW

**Comment by yao-msft** [comment]
Try close and reopen

**Comment by Trenly** [comment]
I've seen a rebase with a force push work occasionally in the past

**Review by Mos0241 — APPROVED** [review]

**Review by JohnMcPMS — DISMISSED** [review]

**Review by ryfu-msft — APPROVED** [review]

**Pull request merged**
