### PR TITLE
Added homepage command using the search command as a base

### LINKED ISSUE #501: Open Manifest's Homepage in default browser via a command
# Description of the new feature/enhancement
I was expecting to have a command that would open the homepage of the manifest without having to use copy paste within the command window itself. 
## Current Process I have to employ
exploring winget's : List of available manifests via 
```cmd
winget show 
```
The above command lists all the manifests. 
looking through the manifests some may interest me and I run 
```cmd
winget show <app.mainfest>
```
This outputs the data of the manifest in a human readable form.

Its at this point i have to Select the URL of the homepage and copy paste it into my browser. 
I was expecting to find an option to open the Homepage URL via the command line. 

# Proposed technical implementation details (optional)

I was epxecting to be able to type something like
```cmd
winget homepage <app.manifest>
```
Expected Functions of this command.
1. This command would [if homepage or other URL, is found in the manifest] take the url and open the url in the user's/systems default browser. 
1. If the homepage is not present in the manifest the output would notify the user the URL was not found in the manifest. 

Example: Scoop home <appName> would open the app's homepage listed in the manifest allowing for exploration. 

# Additional Consideration
I would also consider making at least one informatic URL (be it license[licenseURL], privacy policy[not found in manifest], or homepage url[Homepage]) required in the minimum required.

### PR DESCRIPTION
**Pull request by skyhoshi**
## Summary of the Pull Request
Adds the "homepage" command that when referencing one manifest / app Id it will open the homepage that is within the manifest in the systems default browser.

* If there is no homepage within the manifest it will alert the user to that effect.
* If more than one manifest is found it will list the found manifests and not open a homepage.

## PR Checklist

* [X] Closes #501 
* [X] CLA signed. If not, go over [here](https://cla.opensource.microsoft.com/microsoft/Terminal) and sign the CLA
* [X] Tests added/passed : No documentation on where tests were required/needed/should be preformed. All existing tests pass.
* [X] Requires documentation to be updated : adding new page to https://github.com/skyhoshi/windows-uwp/tree/docs/hub/package-manager/winget
* [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan. Issue number where discussion took place: #xxx  
NOTE, In Response to above: I haven't had a conversation with anyone about the work. and I understand if this is rejected but I do ask that someone explains clearly why. this is one of my first edits on a project where the language is one that i consider myself weak in. and would appreciate this learning opportunity from the community. thanks!

## Detailed Description of the Pull Request / Additional comments
Added a new command that mimics the search function, added locallizable descriptions and added new telemetry call to monitor use of the homepage command and output.
the telemetry action would be to respond to bad actors attempting to include sites and webpages not intended to describe or provide information on the application included within the repository.
The command does a fuzzy lookup on the ID, Name, Monkier and tag fields to provide a list of possible matches, the output includes hints on how to refine or pick a certain manifest from the list. 

## Validation Steps Performed

Demonstration of a list of manifests returned when no query specified

```powershell
.\AppInstallerCLI.exe homepage
```

Results

```txt
Multiple packages found matching input criteria. Please refine the input.
Name                                  Id                                  Version
------------------------------------------------------------------------------------------
Robo3T                                3T.Robo3T                           1.3.1
~~~~~~~~~~~~~~~~~~~ Removed large portion of list for brevity ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Zerotier                              zerotier.zerotier                   1.4.6.0
More than one result was found please refine your query.
```

Demonstration of a list of manifests return from a query

```powershell
.\AppInstallerCLI.exe homepage Microsoft
```

Results

```txt
Multiple packages found matching input criteria. Please refine the input.
Name                      Id                               Version        Match
----------------------------------------------------------------------------------------
PowerBI Desktop           Microsoft.PowerBI                2.82.5858.1161 Tag: microsoft
Mouse and Keyboard Center Microsoft.MouseandKeyboardCenter 12.181.137.0   Tag: microsoft
Smallbasic                Microsoft.SmallBasic             1.2            Tag: microsoft
More than one result was found please refine your query.
```

Demonstration of a single manifest with a homepage.

```powershell
.\AppInstallerCLI.exe homepage Microsoft.VisualStudioCode
```

Results

```txt
Name               Id                         Version
---------------------------------------------------------------
Visual Studio Code Microsoft.VisualStudioCode 1.47.2.17299e413d
Homepage: https://code.visualstudio.com
<OPENS BROWSER TO HOMEPAGE>
```

Demonstration of a Manifest without a homepage.

```powershell
.\AppInstallerCLI.exe homepage PlayStation.PSNow
```

Results

```txt
Name            Id                Version
-----------------------------------------
PlayStation Now PlayStation.PSNow 11.1.2
No Homepage found within manifest
```

Demonstration of a Manifest found with quoted text

```powershell
.\AppInstallerCLI.exe homepage "Visual Studio Code"
```

Results

```txt
Name               Id                         Version
---------------------------------------------------------------
Visual Studio Code Microsoft.VisualStudioCode 1.47.2.17299e413d
Homepage: https://code.visualstudio.com
<OPENS BROWSER TO HOMEPAGE>
```
Demonstration of a Manifest found with quoted text

```powershell
.\AppInstallerCLI.exe homepage  --Name "Visual Studio Code"
```

Results

```txt
Name               Id                         Version
---------------------------------------------------------------
Visual Studio Code Microsoft.VisualStudioCode 1.47.2.17299e413d
Homepage: https://code.visualstudio.com
<OPENS BROWSER TO HOMEPAGE>
```

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-cli/pull/503)

### CODE REVIEW

**Comment by skyhoshi** [comment]
I found an issue with one of the examples 
```
wingetdev homepage --Id Microsoft.VisualStudioCode
```
returns an unexpected error as "Invalid Vector Subscript" which I've interpreted as the inabiltity to parse the ID given.
when I run 

```
wingetdev homepage microsoft.visualstudiocode
```
the command succeds and opens up the web page. 
wingetdev test problem

**Comment by skyhoshi** [comment]
after research this seems to be related to #252 and not related to the changes in this PR.

**Comment by WSLUser** [comment]
Please see https://github.com/microsoft/winget-cli/issues/558, which I think will affect this PR.

**Comment by jsoref** [comment]
At some point you'll need to rebase onto master at which point the spell checker will ask you to add a couple of items to the `expect.txt` file

**Comment by JohnMcPMS** [comment]
Closing due to Terminal's support of hyperlinks and the age of this PR.

**Pull request closed without merging**
