### PR TITLE
Add bootstrap script

### PR DESCRIPTION
**Pull request by cdhunt**
Signed-off-by: Chris Hunt <github@automatedops.com>

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Are you working against an Issue? yes #2434

-----
I'm proposing a simple install script that can be run to bootstrap a new system with winget. Ideally, it would be aliased to `aka.ms/install-winget`.

eg: 
```powershell
iex ((iwr 'https://raw.githubusercontent.com/cdhunt/winget-cli/main/tools/install-winget.ps1' -UseBasicParsing).Content)
```

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2474)

### CODE REVIEW

**Review by vedantmgoyal2009 — COMMENTED** [review]
https://github.com/microsoft/winget-pkgs/blob/master/Tools/WingetVersionManager.ps1

I think the above script does the same work, and also allows choosing versions.

**Comment by cdhunt** [comment]
It does appear to do the same thing (and more), but it crashes/terminates PowerShell when I try to `IEX` it.

I'll poke around and see if I can figure out why it's exiting for me.

**Comment by denelon** [comment]
@cdhunt we're working on something similar internally to help with "ensuring" the latest stable release is installed. I'm mentioning @lechacon who is looking at this.

**Comment by denelon** [comment]
@cdhunt have you had a chance to look at the DSC Resources for WinGet?

There are still a couple of gaps related to the App Execution Alias and UI.Xaml dependency, but it's getting very close.

**Comment by Trenly** [comment]
With the latest release of the 1.7 client, the dependencies for WinGet have been updated to be Microsoft.UI.Xaml 2.8 instead of 2.7. @denelon and the team have been working hard putting together documentation around [how to install WinGet on Windows Sandbox](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox) which requires a bootstrap script like this. Additionally, the [Microsoft.WinGet.Client PowerShell Module](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/) has the `Repair-WinGetPackageManager` cmdlet which will bootstrap WinGet automatically. 

I believe these satisfy the request of the original issue for documenting how to install / bootstrap WinGet

-----
##### Close with reason: PR is outdated by more than a year;

**Pull request closed without merging**
