### PR TITLE
Update versions of services and more

### PR DESCRIPTION
**Pull request by skanda890**
- [X] I have signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs).
- [X] This pull request is related to #4659.
-----
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-cli/pull/4663)

### CODE REVIEW

**Comment by skanda890** [comment]
@Trenly, check this.

**Comment by Trenly** [comment]
Still has 1700 commits
IMG_5840

**Comment by skanda890** [comment]
Okay, wait.

**Comment by skanda890** [comment]
> Still has 1700 commits IMG_5840

But it has more changes than 2 changes, that is why it has more commits.

**Comment by denelon** [comment]
@skanda890 you should make sure you update the fork/branch you're working on to the latest version so that we're only seeing the small changes you're proposing in your PRs.

**Pull request closed without merging**
