### PR TITLE
fix passing null parameters to Find-WinGetPackage

### PR DESCRIPTION
**Pull request by bftblomster**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Are you working against an Issue? Issue 2091 https://github.com/microsoft/winget-cli/issues/2091

-----
This PR enables all cmdlets in the module and makes Install-WinGetPackage actually work. There may be other stuff wrong with the other cmdlets but I didn't test the other ones thoroughly.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2092)

### CODE REVIEW

**Comment by denelon** [comment]
It looks like I didn't get "--verbose-log" in there. Did I miss something?

**Comment by bftblomster** [comment]
> It looks like I didn't get "--verbose-log" in there. Did I miss something?

I don't see that in the original version. Maybe it wasn't added?

**Comment by denelon** [comment]
That wouldn't surprise me! Would you mind adding it?

**Comment by bftblomster** [comment]
> That wouldn't surprise me! Would you mind adding it?

From what I can tell is Invoke-WinGetCommand would need to have verbose logging support and I think that's outside my abilities to add.

**Comment by denelon** [comment]
No worries then 😊. I'll try to remember to add it after this PR is resolved.

**Comment by bftblomster** [comment]
I came up with a function for getting already installed winget packages. I've just tested this on the Visual C++ Redistributables. It gives me the output I need.
```
function Get-LocalWinGetPackage {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory)]
        [string]
        $Id
    )
    $Command = "winget list --id $Id --exact --count 1 --source winget"
    $CommandOutputRaw = Invoke-Expression -Command $Command

    $Index = 0
    ForEach ($Line in $CommandOutputRaw) {
        If ($Line -match "^---.") {
            $TitleLine = $CommandOutputRaw.Get($Index - 1)
            $ResultLine = $CommandOutputRaw.Get($Index + 1)
            break
        }
        $Index++
    }
    $Titles = @()
    $TitleLineHeadings = $TitleLine.Split(' ') | Select-String -Pattern "[a-z]"
    ForEach ($TitleHeading in $TitleLineHeadings) {
        $Title = [PSCustomObject]@{
            TitleName = $TitleHeading.ToString()
            TitleStartIndex = $TitleLine.IndexOf($TitleHeading.ToString())
            TitleLength = $TitleHeading.ToString().Length
        }
        $Titles += $Title
    }
    $WinGetPackage = New-Object PSObject
    $Index = 0
    ForEach ($Title in $Titles) {
        If (($Index + 1) -eq $Titles.Count) {
            $ResultLength = $ResultLine.Length - $Titles[$Index].TitleStartIndex
        } Else {
            $ResultLength = $Titles[$Index + 1].TitleStartIndex - $Title.TitleStartIndex
        }
        $VersionTitles = @("Version","Available")
        If ($VersionTitles -contains $Title.TitleName) {
            Add-Member -InputObject $WinGetPackage -MemberType NoteProperty -Name $Title.TitleName -Value ([System.Version]$ResultLine.Substring($Title.TitleStartIndex, $ResultLength).Trim())
        } Else {
            Add-Member -InputObject $WinGetPackage -MemberType NoteProperty -Name $Title.TitleName -Value $ResultLine.Substring($Title.TitleStartIndex, $ResultLength).Trim()
        }
        $Index++
    }
    return $WinGetPackage
}
```

**Pull request merged**
