### PR TITLE
Set url max length to 2048

### LINKED ISSUE #922: Update URL Max length to 2048
# Update URL Max length to 2048

Browsers typically support up to 2048 characters in URLs.  The manifest schema caps URLs at 2000 characters.
We should align to the 2048 length.

### PR DESCRIPTION
**Pull request by yao-msft**
Fixes #922 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/928)

### CODE REVIEW

**Review by JohnMcPMS — APPROVED** [review]

**Comment by JohnMcPMS** [comment]
If you want to run the tests, I think you will have to manually schedule a build as the PR trigger is only on the code.

**Comment by yao-msft** [comment]
> If you want to run the tests, I think you will have to manually schedule a build as the PR trigger is only on the code.

Done

**Review by jonesk7734 — COMMENTED** [review]
Ok

**Pull request merged**
