### PR TITLE
Use check-spelling/check-spelling@v0.0.20

### PR DESCRIPTION
**Pull request by jsoref**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Are you working against an Issue?

-----

Upgrades to [v0.0.20](https://github.com/check-spelling/check-spelling/releases/tag/v0.0.20)

The upgrade will automatically collapse the most recent PR comment when a PR is updated.

Refreshes the workflow based on
https://github.com/check-spelling/spell-check-this/blob/744c66e2140fd8acaf5388efd0db3727d010d6e9/.github/workflows/spelling.yml

The refresh implements reduced privilege for the workflow, changes the minimum word length from `2` to `3` (the default), and adds `line_forbidden.patterns` (including duplicate word detection).

If the `Gitlab` -> `GitLab` changes are problematic, the commit can be dropped and the entry removed from `.github/actions/spelling/line_forbidden.patterns`.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-cli/pull/2467)

### CODE REVIEW

**Comment by jsoref** [comment]
(Those items can go away after this merges.)

**Review by vedantmgoyal2009 — COMMENTED** [review]
Looks good to me!

**Review by ryfu-msft — APPROVED** [review]

**Comment by jsoref** [comment]
@ryfu-msft: did something go wrong?

**Comment by ryfu-msft** [comment]
I meant to click view details, and accidentally clicked revert and it created that commit...

**Comment by Trenly** [comment]
@jsoref - Does [winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/master/.github/workflows/spellCheck.yaml) need to be updated? It seems you have some great tools to help clean up the dictionary files

**Comment by jsoref** [comment]
@Trenly: yes, it absolutely should be, I'm not sure why I didn't find that when I was looking.

**Comment by Trenly** [comment]
> @Trenly: yes, it absolutely should be, I'm not sure why I didn't find that when I was looking.

Would you be able to open the PR for it? I'm not confident that I have the know-how on the implementation details

**Comment by jsoref** [comment]
Yeah, working on it. Currently tripping on the GitHub outage.

**Pull request merged**
